server:
  port: 8080

database:
  host: host
  port: port
  user: user
  password: "password"
  name: name
  charset: utf8mb4

file:
  upload:
    path: path
    max_size: 104857600  # 100MB
    allowed_types: "jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,txt,zip,rar"